### ISSUE TITLE
对接 请教

### ISSUE THREAD

**Issue by cloudfreexiao** [fyc/DKSingleSDK_DemoProject312#1]
你好 请问 下 我在对接 百度sdk 时候 出现获取权限获取问题
日志如下
https://gist.github.com/cloudfreexiao/1a7164e49447ebddaaad9eacaf347561
我在 cocos 的 AppActivity 中 增加 如下 代码 依然 报错 但是 我 debug 确认是 获取权限成功的 请问有什么其他原因吗

`	private boolean requestSettingActivity() {
		boolean permission;

		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
			permission = Settings.System.canWrite(this);
		} else {
			permission = ContextCompat.checkSelfPermission(this,
					Manifest.permission.WRITE_SETTINGS) == PackageManager.PERMISSION_GRANTED;
		}
		if (permission) {
			return true;
		} else {
			if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M) {
				Intent intent = new Intent(Settings.ACTION_MANAGE_WRITE_SETTINGS);
				intent.setData(Uri.parse("package:" + this.getPackageName()));
//				intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
//				this.startActivity(intent);

                startActivityForResult(intent, AppActivity.REQUEST_WRITE_SETTINGS);
			} else {
				ActivityCompat.requestPermissions(this,
                        new String[]{Manifest.permission.WRITE_SETTINGS},
                        AppActivity.REQUEST_WRITE_SETTINGS);
			}
			return false;
		}
	}

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == AppActivity.REQUEST_WRITE_SETTINGS) {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && Settings.System.canWrite(this)) {
                Toast.makeText(AppActivity.this, "权限设置成功", Toast.LENGTH_SHORT).show();
            }
        }
    }`

**Comment by fyc** [comment]
cocos的问题我其实不了解。有可能是手机型号、系统版本的问题（国内的各家rom都有自己的一套东西），我觉得和sdk不是太大问题，建议还是谷歌或百度一下吧！

**Comment by fyc** [comment]
> 你好 请问 下 我在对接 百度sdk 时候 出现获取权限获取问题
> 日志如下
> https://gist.github.com/cloudfreexiao/1a7164e49447ebddaaad9eacaf347561
> 我在 cocos 的 AppActivity 中 增加 如下 代码 依然 报错 但是 我 debug 确认是 获取权限成功的 请问有什么其他原因吗
> 
> `	private boolean requestSettingActivity() {
> boolean permission;
> 
> ```
> 	if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
> 		permission = Settings.System.canWrite(this);
> 	} else {
> 		permission = ContextCompat.checkSelfPermission(this,
> 				Manifest.permission.WRITE_SETTINGS) == PackageManager.PERMISSION_GRANTED;
> 	}
> 	if (permission) {
> 		return true;
> 	} else {
> 		if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M) {
> 			Intent intent = new Intent(Settings.ACTION_MANAGE_WRITE_SETTINGS);
> 			intent.setData(Uri.parse("package:" + this.getPackageName()));
> ```
> //	intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
> //	this.startActivity(intent);
> 
> ```
>             startActivityForResult(intent, AppActivity.REQUEST_WRITE_SETTINGS);
> 		} else {
> 			ActivityCompat.requestPermissions(this,
>                     new String[]{Manifest.permission.WRITE_SETTINGS},
>                     AppActivity.REQUEST_WRITE_SETTINGS);
> 		}
> 		return false;
> 	}
> }
> 
> @Override
> public void onActivityResult(int requestCode, int resultCode, Intent data) {
>     super.onActivityResult(requestCode, resultCode, data);
>     if (requestCode == AppActivity.REQUEST_WRITE_SETTINGS) {
>         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && Settings.System.canWrite(this)) {
>             Toast.makeText(AppActivity.this, "权限设置成功", Toast.LENGTH_SHORT).show();
>         }
>     }
> }`
> ```

cocos的问题我其实不了解。有可能是手机型号、系统版本的问题（国内的各家rom都有自己的一套东西），我觉得和sdk不是太大问题，建议还是谷歌或百度一下吧！

**Comment by cloudfreexiao** [comment]
好的
